export type ElementGroup =
  | "alkali-metal"
  | "alkaline-earth-metal"
  | "transition-metal"
  | "post-transition-metal"
  | "metalloid"
  | "nonmetal"
  | "halogen"
  | "noble-gas"
  | "lanthanide"
  | "actinide"

export const elementGroups: ElementGroup[] = [
  "alkali-metal",
  "alkaline-earth-metal",
  "transition-metal",
  "post-transition-metal",
  "metalloid",
  "nonmetal",
  "halogen",
  "noble-gas",
  "lanthanide",
  "actinide",
]

export interface Element {
  atomicNumber: number
  symbol: string
  name: string
  atomicMass: number
  category: ElementGroup
  group: number | null
  period: number
  block: string
  electronConfiguration: string
  electronegativity: number | null
  oxidationStates: string | null
  density: number | null
  meltingPoint: number | null
  boilingPoint: number | null
  yearDiscovered: number | null
  discoverer: string | null
  description: string
}

export const elements: Element[] = [
  {
    atomicNumber: 1,
    symbol: "H",
    name: "Hydrogen",
    atomicMass: 1.008,
    category: "nonmetal",
    group: 1,
    period: 1,
    block: "s",
    electronConfiguration: "1s¹",
    electronegativity: 2.2,
    oxidationStates: "-1, +1",
    density: 0.0000899,
    meltingPoint: 14.01,
    boilingPoint: 20.28,
    yearDiscovered: 1766,
    discoverer: "Henry Cavendish",
    description:
      "Hydrogen is the lightest element and the most abundant chemical substance in the universe, constituting roughly 75% of all normal matter.",
  },
  {
    atomicNumber: 2,
    symbol: "He",
    name: "Helium",
    atomicMass: 4.0026,
    category: "noble-gas",
    group: 18,
    period: 1,
    block: "s",
    electronConfiguration: "1s²",
    electronegativity: null,
    oxidationStates: "0",
    density: 0.0001785,
    meltingPoint: 0.95,
    boilingPoint: 4.22,
    yearDiscovered: 1868,
    discoverer: "Pierre Janssen",
    description:
      "Helium is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas, the first in the noble gas group in the periodic table.",
  },
  {
    atomicNumber: 3,
    symbol: "Li",
    name: "Lithium",
    atomicMass: 6.94,
    category: "alkali-metal",
    group: 1,
    period: 2,
    block: "s",
    electronConfiguration: "[He] 2s¹",
    electronegativity: 0.98,
    oxidationStates: "+1",
    density: 0.534,
    meltingPoint: 453.69,
    boilingPoint: 1560,
    yearDiscovered: 1817,
    discoverer: "Johan August Arfwedson",
    description:
      "Lithium is a soft, silvery-white alkali metal. Under standard conditions, it is the lightest metal and the lightest solid element.",
  },
  {
    atomicNumber: 4,
    symbol: "Be",
    name: "Beryllium",
    atomicMass: 9.0122,
    category: "alkaline-earth-metal",
    group: 2,
    period: 2,
    block: "s",
    electronConfiguration: "[He] 2s²",
    electronegativity: 1.57,
    oxidationStates: "+2",
    density: 1.85,
    meltingPoint: 1560,
    boilingPoint: 2742,
    yearDiscovered: 1798,
    discoverer: "Louis Nicolas Vauquelin",
    description:
      "Beryllium is a relatively rare element in the universe. It is a divalent element which occurs naturally only in combination with other elements.",
  },
  {
    atomicNumber: 5,
    symbol: "B",
    name: "Boron",
    atomicMass: 10.81,
    category: "metalloid",
    group: 13,
    period: 2,
    block: "p",
    electronConfiguration: "[He] 2s² 2p¹",
    electronegativity: 2.04,
    oxidationStates: "+3",
    density: 2.34,
    meltingPoint: 2349,
    boilingPoint: 4200,
    yearDiscovered: 1808,
    discoverer: "Joseph Louis Gay-Lussac",
    description:
      "Boron is a chemical element with symbol B and atomic number 5. It is a low-abundance element that is present in the Earth's crust.",
  },
  {
    atomicNumber: 6,
    symbol: "C",
    name: "Carbon",
    atomicMass: 12.011,
    category: "nonmetal",
    group: 14,
    period: 2,
    block: "p",
    electronConfiguration: "[He] 2s² 2p²",
    electronegativity: 2.55,
    oxidationStates: "-4, -3, -2, -1, +1, +2, +3, +4",
    density: 2.267,
    meltingPoint: 3800,
    boilingPoint: 4300,
    yearDiscovered: null,
    discoverer: "Ancient",
    description:
      "Carbon is a chemical element with symbol C and atomic number 6. It is nonmetallic and tetravalent—making four electrons available to form covalent chemical bonds.",
  },
  {
    atomicNumber: 7,
    symbol: "N",
    name: "Nitrogen",
    atomicMass: 14.007,
    category: "nonmetal",
    group: 15,
    period: 2,
    block: "p",
    electronConfiguration: "[He] 2s² 2p³",
    electronegativity: 3.04,
    oxidationStates: "-3, -2, -1, +1, +2, +3, +4, +5",
    density: 0.001251,
    meltingPoint: 63.15,
    boilingPoint: 77.36,
    yearDiscovered: 1772,
    discoverer: "Daniel Rutherford",
    description:
      "Nitrogen is a chemical element with symbol N and atomic number 7. It is the lightest member of group 15 of the periodic table, often called the pnictogens.",
  },
  {
    atomicNumber: 8,
    symbol: "O",
    name: "Oxygen",
    atomicMass: 15.999,
    category: "nonmetal",
    group: 16,
    period: 2,
    block: "p",
    electronConfiguration: "[He] 2s² 2p⁴",
    electronegativity: 3.44,
    oxidationStates: "-2, -1, +1, +2",
    density: 0.001429,
    meltingPoint: 54.36,
    boilingPoint: 90.2,
    yearDiscovered: 1774,
    discoverer: "Carl Wilhelm Scheele",
    description:
      "Oxygen is a chemical element with symbol O and atomic number 8. It is a member of the chalcogen group on the periodic table, a highly reactive nonmetal.",
  },
  {
    atomicNumber: 9,
    symbol: "F",
    name: "Fluorine",
    atomicMass: 18.998,
    category: "halogen",
    group: 17,
    period: 2,
    block: "p",
    electronConfiguration: "[He] 2s² 2p⁵",
    electronegativity: 3.98,
    oxidationStates: "-1",
    density: 0.001696,
    meltingPoint: 53.53,
    boilingPoint: 85.03,
    yearDiscovered: 1886,
    discoverer: "Henri Moissan",
    description:
      "Fluorine is a chemical element with symbol F and atomic number 9. It is the lightest halogen and exists as a highly toxic pale yellow diatomic gas at standard conditions.",
  },
  {
    atomicNumber: 10,
    symbol: "Ne",
    name: "Neon",
    atomicMass: 20.18,
    category: "noble-gas",
    group: 18,
    period: 2,
    block: "p",
    electronConfiguration: "[He] 2s² 2p⁶",
    electronegativity: null,
    oxidationStates: "0",
    density: 0.0008999,
    meltingPoint: 24.56,
    boilingPoint: 27.07,
    yearDiscovered: 1898,
    discoverer: "William Ramsay",
    description:
      "Neon is a chemical element with symbol Ne and atomic number 10. It is a noble gas. Neon is a colorless, odorless, inert monatomic gas under standard conditions.",
  },
  {
    atomicNumber: 11,
    symbol: "Na",
    name: "Sodium",
    atomicMass: 22.99,
    category: "alkali-metal",
    group: 1,
    period: 3,
    block: "s",
    electronConfiguration: "[Ne] 3s¹",
    electronegativity: 0.93,
    oxidationStates: "+1",
    density: 0.968,
    meltingPoint: 370.87,
    boilingPoint: 1156,
    yearDiscovered: 1807,
    discoverer: "Humphry Davy",
    description:
      "Sodium is a chemical element with symbol Na and atomic number 11. It is a soft, silvery-white, highly reactive metal.",
  },
  {
    atomicNumber: 12,
    symbol: "Mg",
    name: "Magnesium",
    atomicMass: 24.305,
    category: "alkaline-earth-metal",
    group: 2,
    period: 3,
    block: "s",
    electronConfiguration: "[Ne] 3s²",
    electronegativity: 1.31,
    oxidationStates: "+2",
    density: 1.738,
    meltingPoint: 923,
    boilingPoint: 1363,
    yearDiscovered: 1808,
    discoverer: "Humphry Davy",
    description:
      "Magnesium is a chemical element with symbol Mg and atomic number 12. It is a shiny gray solid which bears a close physical resemblance to the other five elements in the second column of the periodic table.",
  },
  {
    atomicNumber: 13,
    symbol: "Al",
    name: "Aluminium",
    atomicMass: 26.982,
    category: "post-transition-metal",
    group: 13,
    period: 3,
    block: "p",
    electronConfiguration: "[Ne] 3s² 3p¹",
    electronegativity: 1.61,
    oxidationStates: "+3",
    density: 2.7,
    meltingPoint: 933.47,
    boilingPoint: 2792,
    yearDiscovered: 1825,
    discoverer: "Hans Christian Ørsted",
    description:
      "Aluminum is a chemical element with symbol Al and atomic number 13. It is a silvery-white, soft, nonmagnetic, ductile metal in the boron group.",
  },
  {
    atomicNumber: 14,
    symbol: "Si",
    name: "Silicon",
    atomicMass: 28.085,
    category: "metalloid",
    group: 14,
    period: 3,
    block: "p",
    electronConfiguration: "[Ne] 3s² 3p²",
    electronegativity: 1.9,
    oxidationStates: "-4, +2, +4",
    density: 2.33,
    meltingPoint: 1687,
    boilingPoint: 3538,
    yearDiscovered: 1824,
    discoverer: "Jöns Jacob Berzelius",
    description:
      "Silicon is a chemical element with symbol Si and atomic number 14. It is a hard and brittle crystalline solid with a blue-grey metallic lustre.",
  },
  {
    atomicNumber: 15,
    symbol: "P",
    name: "Phosphorus",
    atomicMass: 30.974,
    category: "nonmetal",
    group: 15,
    period: 3,
    block: "p",
    electronConfiguration: "[Ne] 3s² 3p³",
    electronegativity: 2.19,
    oxidationStates: "-3, +1, +3, +5",
    density: 1.82,
    meltingPoint: 317.3,
    boilingPoint: 553.6,
    yearDiscovered: 1669,
    discoverer: "Hennig Brand",
    description:
      "Phosphorus is a chemical element with symbol P and atomic number 15. As an element, phosphorus exists in two major forms—white phosphorus and red phosphorus.",
  },
  {
    atomicNumber: 16,
    symbol: "S",
    name: "Sulfur",
    atomicMass: 32.06,
    category: "nonmetal",
    group: 16,
    period: 3,
    block: "p",
    electronConfiguration: "[Ne] 3s² 3p⁴",
    electronegativity: 2.58,
    oxidationStates: "-2, +2, +4, +6",
    density: 2.07,
    meltingPoint: 388.36,
    boilingPoint: 717.87,
    yearDiscovered: null,
    discoverer: "Ancient",
    description:
      "Sulfur is a chemical element with symbol S and atomic number 16. It is abundant, multivalent, and nonmetallic.",
  },
  {
    atomicNumber: 17,
    symbol: "Cl",
    name: "Chlorine",
    atomicMass: 35.45,
    category: "halogen",
    group: 17,
    period: 3,
    block: "p",
    electronConfiguration: "[Ne] 3s² 3p⁵",
    electronegativity: 3.16,
    oxidationStates: "-1, +1, +3, +5, +7",
    density: 0.003214,
    meltingPoint: 171.6,
    boilingPoint: 239.11,
    yearDiscovered: 1774,
    discoverer: "Carl Wilhelm Scheele",
    description:
      "Chlorine is a chemical element with symbol Cl and atomic number 17. It is a yellow-green gas at room temperature and is a member of the halogen group of elements.",
  },
  {
    atomicNumber: 18,
    symbol: "Ar",
    name: "Argon",
    atomicMass: 39.948,
    category: "noble-gas",
    group: 18,
    period: 3,
    block: "p",
    electronConfiguration: "[Ne] 3s² 3p⁶",
    electronegativity: null,
    oxidationStates: "0",
    density: 0.0017837,
    meltingPoint: 83.8,
    boilingPoint: 87.3,
    yearDiscovered: 1894,
    discoverer: "Lord Rayleigh",
    description:
      "Argon is a chemical element with symbol Ar and atomic number 18. It is in group 18 of the periodic table and is a noble gas.",
  },
  {
    atomicNumber: 19,
    symbol: "K",
    name: "Potassium",
    atomicMass: 39.098,
    category: "alkali-metal",
    group: 1,
    period: 4,
    block: "s",
    electronConfiguration: "[Ar] 4s¹",
    electronegativity: 0.82,
    oxidationStates: "+1",
    density: 0.89,
    meltingPoint: 336.53,
    boilingPoint: 1032,
    yearDiscovered: 1807,
    discoverer: "Humphry Davy",
    description:
      "Potassium is a chemical element with symbol K and atomic number 19. It was first isolated from potash, the ashes of plants, from which its name derives.",
  },
  {
    atomicNumber: 20,
    symbol: "Ca",
    name: "Calcium",
    atomicMass: 40.078,
    category: "alkaline-earth-metal",
    group: 2,
    period: 4,
    block: "s",
    electronConfiguration: "[Ar] 4s²",
    electronegativity: 1.0,
    oxidationStates: "+2",
    density: 1.55,
    meltingPoint: 1115,
    boilingPoint: 1757,
    yearDiscovered: 1808,
    discoverer: "Humphry Davy",
    description:
      "Calcium is a chemical element with symbol Ca and atomic number 20. As an alkaline earth metal, calcium is a reactive metal that forms a dark oxide-nitride layer when exposed to air.",
  },
  {
    atomicNumber: 21,
    symbol: "Sc",
    name: "Scandium",
    atomicMass: 44.956,
    category: "transition-metal",
    group: 3,
    period: 4,
    block: "d",
    electronConfiguration: "[Ar] 3d¹ 4s²",
    electronegativity: 1.36,
    oxidationStates: "+3",
    density: 2.99,
    meltingPoint: 1814,
    boilingPoint: 3109,
    yearDiscovered: 1879,
    discoverer: "Lars Fredrik Nilson",
    description:
      "Scandium is a chemical element with symbol Sc and atomic number 21. A silvery-white metallic d-block element, it has historically been classified as a rare-earth element.",
  },
  {
    atomicNumber: 22,
    symbol: "Ti",
    name: "Titanium",
    atomicMass: 47.867,
    category: "transition-metal",
    group: 4,
    period: 4,
    block: "d",
    electronConfiguration: "[Ar] 3d² 4s²",
    electronegativity: 1.54,
    oxidationStates: "+2, +3, +4",
    density: 4.5,
    meltingPoint: 1941,
    boilingPoint: 3560,
    yearDiscovered: 1791,
    discoverer: "William Gregor",
    description:
      "Titanium is a chemical element with symbol Ti and atomic number 22. It is a lustrous transition metal with a silver color, low density, and high strength.",
  },
  {
    atomicNumber: 23,
    symbol: "V",
    name: "Vanadium",
    atomicMass: 50.942,
    category: "transition-metal",
    group: 5,
    period: 4,
    block: "d",
    electronConfiguration: "[Ar] 3d³ 4s²",
    electronegativity: 1.63,
    oxidationStates: "+2, +3, +4, +5",
    density: 6.0,
    meltingPoint: 2183,
    boilingPoint: 3680,
    yearDiscovered: 1801,
    discoverer: "Andrés Manuel del Río",
    description:
      "Vanadium is a chemical element with symbol V and atomic number 23. It is a hard, silvery-grey, ductile, malleable transition metal.",
  },
  {
    atomicNumber: 24,
    symbol: "Cr",
    name: "Chromium",
    atomicMass: 51.996,
    category: "transition-metal",
    group: 6,
    period: 4,
    block: "d",
    electronConfiguration: "[Ar] 3d⁵ 4s¹",
    electronegativity: 1.66,
    oxidationStates: "+2, +3, +6",
    density: 7.15,
    meltingPoint: 2180,
    boilingPoint: 2944,
    yearDiscovered: 1797,
    discoverer: "Louis Nicolas Vauquelin",
    description:
      "Chromium is a chemical element with symbol Cr and atomic number 24. It is the first element in group 6. It is a steely-grey, lustrous, hard and brittle transition metal.",
  },
  {
    atomicNumber: 25,
    symbol: "Mn",
    name: "Manganese",
    atomicMass: 54.938,
    category: "transition-metal",
    group: 7,
    period: 4,
    block: "d",
    electronConfiguration: "[Ar] 3d⁵ 4s²",
    electronegativity: 1.55,
    oxidationStates: "+2, +3, +4, +6, +7",
    density: 7.3,
    meltingPoint: 1519,
    boilingPoint: 2334,
    yearDiscovered: 1774,
    discoverer: "Johan Gottlieb Gahn",
    description:
      "Manganese is a chemical element with symbol Mn and atomic number 25. It is not found as a free element in nature; it is often found in minerals in combination with iron.",
  },
  {
    atomicNumber: 26,
    symbol: "Fe",
    name: "Iron",
    atomicMass: 55.845,
    category: "transition-metal",
    group: 8,
    period: 4,
    block: "d",
    electronConfiguration: "[Ar] 3d⁶ 4s²",
    electronegativity: 1.83,
    oxidationStates: "+2, +3, +4, +6",
    density: 7.874,
    meltingPoint: 1811,
    boilingPoint: 3134,
    yearDiscovered: null,
    discoverer: "Ancient",
    description:
      "Iron is a chemical element with symbol Fe and atomic number 26. It is a metal that belongs to the first transition series and group 8 of the periodic table.",
  },
  {
    atomicNumber: 27,
    symbol: "Co",
    name: "Cobalt",
    atomicMass: 58.933,
    category: "transition-metal",
    group: 9,
    period: 4,
    block: "d",
    electronConfiguration: "[Ar] 3d⁷ 4s²",
    electronegativity: 1.88,
    oxidationStates: "+2, +3",
    density: 8.9,
    meltingPoint: 1768,
    boilingPoint: 3200,
    yearDiscovered: 1735,
    discoverer: "Georg Brandt",
    description:
      "Cobalt is a chemical element with symbol Co and atomic number 27. Like nickel, cobalt is found in the Earth's crust only in chemically combined form, save for small deposits found in alloys of natural meteoric iron.",
  },
  {
    atomicNumber: 28,
    symbol: "Ni",
    name: "Nickel",
    atomicMass: 58.693,
    category: "transition-metal",
    group: 10,
    period: 4,
    block: "d",
    electronConfiguration: "[Ar] 3d⁸ 4s²",
    electronegativity: 1.91,
    oxidationStates: "+2, +3",
    density: 8.9,
    meltingPoint: 1728,
    boilingPoint: 3186,
    yearDiscovered: 1751,
    discoverer: "Axel Fredrik Cronstedt",
    description:
      "Nickel is a chemical element with symbol Ni and atomic number 28. It is a silvery-white lustrous metal with a slight golden tinge.",
  },
  {
    atomicNumber: 29,
    symbol: "Cu",
    name: "Copper",
    atomicMass: 63.546,
    category: "transition-metal",
    group: 11,
    period: 4,
    block: "d",
    electronConfiguration: "[Ar] 3d¹⁰ 4s¹",
    electronegativity: 1.9,
    oxidationStates: "+1, +2, +3, +4",
    density: 8.96,
    meltingPoint: 1357.77,
    boilingPoint: 2835,
    yearDiscovered: null,
    discoverer: "Ancient",
    description:
      "Copper is a chemical element with symbol Cu and atomic number 29. It is a soft, malleable, and ductile metal with very high thermal and electrical conductivity.",
  },
  {
    atomicNumber: 30,
    symbol: "Zn",
    name: "Zinc",
    atomicMass: 65.38,
    category: "transition-metal",
    group: 12,
    period: 4,
    block: "d",
    electronConfiguration: "[Ar] 3d¹⁰ 4s²",
    electronegativity: 1.65,
    oxidationStates: "+2",
    density: 7.14,
    meltingPoint: 692.68,
    boilingPoint: 1180,
    yearDiscovered: null,
    discoverer: "Ancient",
    description:
      "Zinc is a chemical element with symbol Zn and atomic number 30. It is the first element in group 12 of the periodic table.",
  },
  {
    atomicNumber: 31,
    symbol: "Ga",
    name: "Gallium",
    atomicMass: 69.723,
    category: "post-transition-metal",
    group: 13,
    period: 4,
    block: "p",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p¹",
    electronegativity: 1.81,
    oxidationStates: "+1, +3",
    density: 5.91,
    meltingPoint: 302.9146,
    boilingPoint: 2673,
    yearDiscovered: 1875,
    discoverer: "Lecoq de Boisbaudran",
    description:
      "Gallium is a chemical element with symbol Ga and atomic number 31. It is in group 13 of the periodic table, and thus has similarities to the other metals of the group, aluminium, indium, and thallium.",
  },
  {
    atomicNumber: 32,
    symbol: "Ge",
    name: "Germanium",
    atomicMass: 72.63,
    category: "metalloid",
    group: 14,
    period: 4,
    block: "p",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p²",
    electronegativity: 2.01,
    oxidationStates: "+2, +4",
    density: 5.323,
    meltingPoint: 1211.4,
    boilingPoint: 3106,
    yearDiscovered: 1886,
    discoverer: "Clemens Winkler",
    description:
      "Germanium is a chemical element with symbol Ge and atomic number 32. It is a lustrous, hard, grayish-white metalloid in the carbon group.",
  },
  {
    atomicNumber: 33,
    symbol: "As",
    name: "Arsenic",
    atomicMass: 74.922,
    category: "metalloid",
    group: 15,
    period: 4,
    block: "p",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p³",
    electronegativity: 2.18,
    oxidationStates: "-3, +3, +5",
    density: 5.727,
    meltingPoint: 1090,
    boilingPoint: 887,
    yearDiscovered: null,
    discoverer: "Ancient",
    description:
      "Arsenic is a chemical element with symbol As and atomic number 33. Arsenic occurs in many minerals, usually in combination with sulfur and metals, but also as a pure elemental crystal.",
  },
  {
    atomicNumber: 34,
    symbol: "Se",
    name: "Selenium",
    atomicMass: 78.971,
    category: "nonmetal",
    group: 16,
    period: 4,
    block: "p",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁴",
    electronegativity: 2.55,
    oxidationStates: "-2, +2, +4, +6",
    density: 4.81,
    meltingPoint: 494,
    boilingPoint: 958,
    yearDiscovered: 1817,
    discoverer: "Jöns Jacob Berzelius",
    description:
      "Selenium is a chemical element with symbol Se and atomic number 34. It is a nonmetal with properties that are intermediate between the elements above and below in the periodic table, sulfur and tellurium.",
  },
  {
    atomicNumber: 35,
    symbol: "Br",
    name: "Bromine",
    atomicMass: 79.904,
    category: "halogen",
    group: 17,
    period: 4,
    block: "p",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁵",
    electronegativity: 2.96,
    oxidationStates: "-1, +1, +3, +5, +7",
    density: 3.1028,
    meltingPoint: 265.8,
    boilingPoint: 332.0,
    yearDiscovered: 1826,
    discoverer: "Antoine Jérôme Balard",
    description:
      "Bromine is a chemical element with symbol Br and atomic number 35. It is the third-lightest halogen, and is a fuming red-brown liquid at room temperature that evaporates readily to form a similarly colored gas.",
  },
  {
    atomicNumber: 36,
    symbol: "Kr",
    name: "Krypton",
    atomicMass: 83.798,
    category: "noble-gas",
    group: 18,
    period: 4,
    block: "p",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁶",
    electronegativity: 3.0,
    oxidationStates: "0, +2",
    density: 0.003733,
    meltingPoint: 115.79,
    boilingPoint: 119.93,
    yearDiscovered: 1898,
    discoverer: "William Ramsay",
    description:
      "Krypton is a chemical element with symbol Kr and atomic number 36. It is a member of group 18 (noble gases) elements. A colorless, odorless, tasteless noble gas, krypton occurs in trace amounts in the atmosphere.",
  },
  {
    atomicNumber: 37,
    symbol: "Rb",
    name: "Rubidium",
    atomicMass: 85.468,
    category: "alkali-metal",
    group: 1,
    period: 5,
    block: "s",
    electronConfiguration: "[Kr] 5s¹",
    electronegativity: 0.82,
    oxidationStates: "+1",
    density: 1.532,
    meltingPoint: 312.46,
    boilingPoint: 961,
    yearDiscovered: 1861,
    discoverer: "Robert Bunsen",
    description:
      "Rubidium is a chemical element with symbol Rb and atomic number 37. Rubidium is a soft, silvery-white metallic element of the alkali metal group, with a standard atomic weight of 85.4678.",
  },
  {
    atomicNumber: 38,
    symbol: "Sr",
    name: "Strontium",
    atomicMass: 87.62,
    category: "alkaline-earth-metal",
    group: 2,
    period: 5,
    block: "s",
    electronConfiguration: "[Kr] 5s²",
    electronegativity: 0.95,
    oxidationStates: "+2",
    density: 2.64,
    meltingPoint: 1050,
    boilingPoint: 1655,
    yearDiscovered: 1790,
    discoverer: "Adair Crawford",
    description:
      "Strontium is a chemical element with symbol Sr and atomic number 38. An alkaline earth metal, strontium is a soft silver-white yellowish metallic element that is highly chemically reactive.",
  },
  {
    atomicNumber: 39,
    symbol: "Y",
    name: "Yttrium",
    atomicMass: 88.906,
    category: "transition-metal",
    group: 3,
    period: 5,
    block: "d",
    electronConfiguration: "[Kr] 4d¹ 5s²",
    electronegativity: 1.22,
    oxidationStates: "+3",
    density: 4.47,
    meltingPoint: 1799,
    boilingPoint: 3609,
    yearDiscovered: 1794,
    discoverer: "Johan Gadolin",
    description:
      "Yttrium is a chemical element with symbol Y and atomic number 39. It is a silvery-metallic transition metal chemically similar to the lanthanides and has often been classified as a 'rare-earth element'.",
  },
  {
    atomicNumber: 40,
    symbol: "Zr",
    name: "Zirconium",
    atomicMass: 91.224,
    category: "transition-metal",
    group: 4,
    period: 5,
    block: "d",
    electronConfiguration: "[Kr] 4d² 5s²",
    electronegativity: 1.33,
    oxidationStates: "+2, +3, +4",
    density: 6.52,
    meltingPoint: 2128,
    boilingPoint: 4682,
    yearDiscovered: 1789,
    discoverer: "Martin Heinrich Klaproth",
    description:
      "Zirconium is a chemical element with symbol Zr and atomic number 40. The name zirconium is taken from the name of the mineral zircon, the most important source of zirconium.",
  },
  {
    atomicNumber: 41,
    symbol: "Nb",
    name: "Niobium",
    atomicMass: 92.906,
    category: "transition-metal",
    group: 5,
    period: 5,
    block: "d",
    electronConfiguration: "[Kr] 4d⁴ 5s¹",
    electronegativity: 1.6,
    oxidationStates: "-1, +2, +3, +4, +5",
    density: 8.57,
    meltingPoint: 2750,
    boilingPoint: 5017,
    yearDiscovered: 1801,
    discoverer: "Charles Hatchett",
    description:
      "Niobium is a chemical element with symbol Nb and atomic number 41. It is a soft, grey, crystalline, ductile transition metal, often found in the minerals pyrochlore and columbite, hence the former name 'columbium'.",
  },
  {
    atomicNumber: 42,
    symbol: "Mo",
    name: "Molybdenum",
    atomicMass: 95.95,
    category: "transition-metal",
    group: 6,
    period: 5,
    block: "d",
    electronConfiguration: "[Kr] 4d⁵ 5s¹",
    electronegativity: 2.16,
    oxidationStates: "-2, -1, +1, +2, +3, +4, +5, +6",
    density: 10.28,
    meltingPoint: 2896,
    boilingPoint: 4912,
    yearDiscovered: 1778,
    discoverer: "Carl Wilhelm Scheele",
    description:
      "Molybdenum is a chemical element with symbol Mo and atomic number 42. The name is from Neo-Latin molybdaenum, from Ancient Greek Μόλυβδος molybdos, meaning lead, since its ores were confused with lead ores.",
  },
  {
    atomicNumber: 43,
    symbol: "Tc",
    name: "Technetium",
    atomicMass: 98,
    category: "transition-metal",
    group: 7,
    period: 5,
    block: "d",
    electronConfiguration: "[Kr] 4d⁵ 5s²",
    electronegativity: 1.9,
    oxidationStates: "+4, +5, +6, +7",
    density: 11.5,
    meltingPoint: 2430,
    boilingPoint: 4538,
    yearDiscovered: 1937,
    discoverer: "Carlo Perrier",
    description:
      "Technetium is a chemical element with symbol Tc and atomic number 43. It is the lightest element whose isotopes are all radioactive; none are stable, excluding the fully ionized state of ⁹⁷Tc.",
  },
  {
    atomicNumber: 44,
    symbol: "Ru",
    name: "Ruthenium",
    atomicMass: 101.07,
    category: "transition-metal",
    group: 8,
    period: 5,
    block: "d",
    electronConfiguration: "[Kr] 4d⁷ 5s¹",
    electronegativity: 2.2,
    oxidationStates: "-2, +1, +2, +3, +4, +5, +6, +7, +8",
    density: 12.45,
    meltingPoint: 2607,
    boilingPoint: 4423,
    yearDiscovered: 1844,
    discoverer: "Karl Ernst Claus",
    description:
      "Ruthenium is a chemical element with symbol Ru and atomic number 44. It is a rare transition metal belonging to the platinum group of the periodic table.",
  },
  {
    atomicNumber: 45,
    symbol: "Rh",
    name: "Rhodium",
    atomicMass: 102.91,
    category: "transition-metal",
    group: 9,
    period: 5,
    block: "d",
    electronConfiguration: "[Kr] 4d⁸ 5s¹",
    electronegativity: 2.28,
    oxidationStates: "-1, +1, +2, +3, +4, +5, +6",
    density: 12.41,
    meltingPoint: 2237,
    boilingPoint: 3968,
    yearDiscovered: 1803,
    discoverer: "William Hyde Wollaston",
    description:
      "Rhodium is a chemical element with symbol Rh and atomic number 45. It is a rare, silvery-white, hard, corrosion-resistant, and chemically inert transition metal.",
  },
  {
    atomicNumber: 46,
    symbol: "Pd",
    name: "Palladium",
    atomicMass: 106.42,
    category: "transition-metal",
    group: 10,
    period: 5,
    block: "d",
    electronConfiguration: "[Kr] 4d¹⁰",
    electronegativity: 2.2,
    oxidationStates: "+1, +2, +3, +4",
    density: 12.023,
    meltingPoint: 1828.05,
    boilingPoint: 3236,
    yearDiscovered: 1803,
    discoverer: "William Hyde Wollaston",
    description:
      "Palladium is a chemical element with symbol Pd and atomic number 46. It is a rare and lustrous silvery-white metal discovered in 1803 by William Hyde Wollaston.",
  },
  {
    atomicNumber: 47,
    symbol: "Ag",
    name: "Silver",
    atomicMass: 107.87,
    category: "transition-metal",
    group: 11,
    period: 5,
    block: "d",
    electronConfiguration: "[Kr] 4d¹⁰ 5s¹",
    electronegativity: 1.93,
    oxidationStates: "+1, +2, +3",
    density: 10.49,
    meltingPoint: 1234.93,
    boilingPoint: 2435,
    yearDiscovered: null,
    discoverer: "Ancient",
    description:
      "Silver is a chemical element with symbol Ag and atomic number 47. A soft, white, lustrous transition metal, it exhibits the highest electrical conductivity, thermal conductivity, and reflectivity of any metal.",
  },
  {
    atomicNumber: 48,
    symbol: "Cd",
    name: "Cadmium",
    atomicMass: 112.41,
    category: "transition-metal",
    group: 12,
    period: 5,
    block: "d",
    electronConfiguration: "[Kr] 4d¹⁰ 5s²",
    electronegativity: 1.69,
    oxidationStates: "+2",
    density: 8.65,
    meltingPoint: 594.22,
    boilingPoint: 1040,
    yearDiscovered: 1817,
    discoverer: "Karl Samuel Leberecht Hermann",
    description:
      "Cadmium is a chemical element with symbol Cd and atomic number 48. This soft, bluish-white metal is chemically similar to the two other stable metals in group 12, zinc and mercury.",
  },
  {
    atomicNumber: 49,
    symbol: "In",
    name: "Indium",
    atomicMass: 114.82,
    category: "post-transition-metal",
    group: 13,
    period: 5,
    block: "p",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p¹",
    electronegativity: 1.78,
    oxidationStates: "+1, +2, +3",
    density: 7.31,
    meltingPoint: 429.75,
    boilingPoint: 2345,
    yearDiscovered: 1863,
    discoverer: "Ferdinand Reich",
    description:
      "Indium is a chemical element with symbol In and atomic number 49. It is a post-transition metallic element that is rare in Earth's crust.",
  },
  {
    atomicNumber: 50,
    symbol: "Sn",
    name: "Tin",
    atomicMass: 118.71,
    category: "post-transition-metal",
    group: 14,
    period: 5,
    block: "p",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p²",
    electronegativity: 1.96,
    oxidationStates: "-4, +2, +4",
    density: 7.31,
    meltingPoint: 505.08,
    boilingPoint: 2875,
    yearDiscovered: null,
    discoverer: "Ancient",
    description:
      "Tin is a chemical element with symbol Sn and atomic number 50. It is a post-transition metal in group 14 of the periodic table.",
  },
  {
    atomicNumber: 51,
    symbol: "Sb",
    name: "Antimony",
    atomicMass: 121.76,
    category: "metalloid",
    group: 15,
    period: 5,
    block: "p",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p³",
    electronegativity: 2.05,
    oxidationStates: "-3, +3, +5",
    density: 6.697,
    meltingPoint: 903.78,
    boilingPoint: 1860,
    yearDiscovered: null,
    discoverer: "Ancient",
    description:
      "Antimony is a chemical element with symbol Sb and atomic number 51. A lustrous gray metalloid, it is found in nature mainly as the sulfide mineral stibnite.",
  },
  {
    atomicNumber: 52,
    symbol: "Te",
    name: "Tellurium",
    atomicMass: 127.6,
    category: "metalloid",
    group: 16,
    period: 5,
    block: "p",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁴",
    electronegativity: 2.1,
    oxidationStates: "-2, +2, +4, +6",
    density: 6.24,
    meltingPoint: 722.66,
    boilingPoint: 1261,
    yearDiscovered: 1782,
    discoverer: "Franz-Joseph Müller von Reichenstein",
    description:
      "Tellurium is a chemical element with symbol Te and atomic number 52. It is a brittle, mildly toxic, rare, silver-white metalloid.",
  },
  {
    atomicNumber: 53,
    symbol: "I",
    name: "Iodine",
    atomicMass: 126.9,
    category: "halogen",
    group: 17,
    period: 5,
    block: "p",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁵",
    electronegativity: 2.66,
    oxidationStates: "-1, +1, +3, +5, +7",
    density: 4.933,
    meltingPoint: 386.85,
    boilingPoint: 457.4,
    yearDiscovered: 1811,
    discoverer: "Bernard Courtois",
    description:
      "Iodine is a chemical element with symbol I and atomic number 53. The name is from Greek ἰοειδής ioeidēs, meaning violet or purple, due to the color of elemental iodine vapor.",
  },
  {
    atomicNumber: 54,
    symbol: "Xe",
    name: "Xenon",
    atomicMass: 131.29,
    category: "noble-gas",
    group: 18,
    period: 5,
    block: "p",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁶",
    electronegativity: 2.6,
    oxidationStates: "0, +2, +4, +6, +8",
    density: 0.005887,
    meltingPoint: 161.4,
    boilingPoint: 165.03,
    yearDiscovered: 1898,
    discoverer: "William Ramsay",
    description:
      "Xenon is a chemical element with symbol Xe and atomic number 54. It is a colorless, dense, odorless noble gas found in the Earth's atmosphere in trace amounts.",
  },
  {
    atomicNumber: 55,
    symbol: "Cs",
    name: "Cesium",
    atomicMass: 132.91,
    category: "alkali-metal",
    group: 1,
    period: 6,
    block: "s",
    electronConfiguration: "[Xe] 6s¹",
    electronegativity: 0.79,
    oxidationStates: "+1",
    density: 1.93,
    meltingPoint: 301.59,
    boilingPoint: 944,
    yearDiscovered: 1860,
    discoverer: "Robert Bunsen",
    description:
      "Cesium is a chemical element with symbol Cs and atomic number 55. It is a soft, silvery-golden alkali metal with a melting point of 28.5 °C, which makes it one of only five elemental metals that are liquid at or near room temperature.",
  },
  {
    atomicNumber: 56,
    symbol: "Ba",
    name: "Barium",
    atomicMass: 137.33,
    category: "alkaline-earth-metal",
    group: 2,
    period: 6,
    block: "s",
    electronConfiguration: "[Xe] 6s²",
    electronegativity: 0.89,
    oxidationStates: "+2",
    density: 3.51,
    meltingPoint: 1000,
    boilingPoint: 2170,
    yearDiscovered: 1808,
    discoverer: "Humphry Davy",
    description:
      "Barium is a chemical element with symbol Ba and atomic number 56. It is the fifth element in group 2 and is a soft, silvery alkaline earth metal.",
  },
  {
    atomicNumber: 57,
    symbol: "La",
    name: "Lanthanum",
    atomicMass: 138.91,
    category: "lanthanide",
    group: 3,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 5d¹ 6s²",
    electronegativity: 1.1,
    oxidationStates: "+3",
    density: 6.145,
    meltingPoint: 1193,
    boilingPoint: 3737,
    yearDiscovered: 1839,
    discoverer: "Carl Gustaf Mosander",
    description:
      "Lanthanum is a chemical element with symbol La and atomic number 57. It is a soft, ductile, silvery-white metal that tarnishes rapidly when exposed to air and is soft enough to be cut with a knife.",
  },
  {
    atomicNumber: 58,
    symbol: "Ce",
    name: "Cerium",
    atomicMass: 140.12,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f¹ 5d¹ 6s²",
    electronegativity: 1.12,
    oxidationStates: "+3, +4",
    density: 6.77,
    meltingPoint: 1068,
    boilingPoint: 3716,
    yearDiscovered: 1803,
    discoverer: "Martin Heinrich Klaproth",
    description:
      "Cerium is a chemical element with symbol Ce and atomic number 58. It is a soft, silvery, ductile metal which easily oxidizes in air.",
  },
  {
    atomicNumber: 59,
    symbol: "Pr",
    name: "Praseodymium",
    atomicMass: 140.91,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f³ 6s²",
    electronegativity: 1.13,
    oxidationStates: "+3, +4",
    density: 6.77,
    meltingPoint: 1208,
    boilingPoint: 3793,
    yearDiscovered: 1885,
    discoverer: "Carl Auer von Welsbach",
    description:
      "Praseodymium is a chemical element with symbol Pr and atomic number 59. It is the third member of the lanthanide series and is traditionally considered to be one of the rare-earth metals.",
  },
  {
    atomicNumber: 60,
    symbol: "Nd",
    name: "Neodymium",
    atomicMass: 144.24,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f⁴ 6s²",
    electronegativity: 1.14,
    oxidationStates: "+3",
    density: 7.01,
    meltingPoint: 1297,
    boilingPoint: 3347,
    yearDiscovered: 1885,
    discoverer: "Carl Auer von Welsbach",
    description:
      "Neodymium is a chemical element with symbol Nd and atomic number 60. It is a soft silvery metal that tarnishes in air.",
  },
  {
    atomicNumber: 61,
    symbol: "Pm",
    name: "Promethium",
    atomicMass: 145,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f⁵ 6s²",
    electronegativity: 1.13,
    oxidationStates: "+3",
    density: 7.26,
    meltingPoint: 1315,
    boilingPoint: 3273,
    yearDiscovered: 1945,
    discoverer: "Jacob A. Marinsky",
    description:
      "Promethium is a chemical element with symbol Pm and atomic number 61. All of its isotopes are radioactive; it is extremely rare, with only about 500–600 grams naturally occurring in Earth's crust at any given time.",
  },
  {
    atomicNumber: 62,
    symbol: "Sm",
    name: "Samarium",
    atomicMass: 150.36,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f⁶ 6s²",
    electronegativity: 1.17,
    oxidationStates: "+2, +3",
    density: 7.52,
    meltingPoint: 1345,
    boilingPoint: 2067,
    yearDiscovered: 1879,
    discoverer: "Paul Émile Lecoq de Boisbaudran",
    description:
      "Samarium is a chemical element with symbol Sm and atomic number 62. It is a moderately hard silvery metal that slowly oxidizes in air.",
  },
  {
    atomicNumber: 63,
    symbol: "Eu",
    name: "Europium",
    atomicMass: 151.96,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f⁷ 6s²",
    electronegativity: 1.2,
    oxidationStates: "+2, +3",
    density: 5.24,
    meltingPoint: 1099,
    boilingPoint: 1802,
    yearDiscovered: 1901,
    discoverer: "Eugène-Anatole Demarçay",
    description:
      "Europium is a chemical element with symbol Eu and atomic number 63. It is named after the continent of Europe.",
  },
  {
    atomicNumber: 64,
    symbol: "Gd",
    name: "Gadolinium",
    atomicMass: 157.25,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f⁷ 5d¹ 6s²",
    electronegativity: 1.2,
    oxidationStates: "+3",
    density: 7.9,
    meltingPoint: 1585,
    boilingPoint: 3546,
    yearDiscovered: 1880,
    discoverer: "Jean Charles Galissard de Marignac",
    description:
      "Gadolinium is a chemical element with symbol Gd and atomic number 64. It is a silvery-white, malleable and ductile rare-earth metal.",
  },
  {
    atomicNumber: 65,
    symbol: "Tb",
    name: "Terbium",
    atomicMass: 158.93,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f⁹ 6s²",
    electronegativity: 1.2,
    oxidationStates: "+3, +4",
    density: 8.23,
    meltingPoint: 1629,
    boilingPoint: 3503,
    yearDiscovered: 1843,
    discoverer: "Carl Gustaf Mosander",
    description:
      "Terbium is a chemical element with symbol Tb and atomic number 65. It is a silvery-white, rare earth metal that is malleable, ductile, and soft enough to be cut with a knife.",
  },
  {
    atomicNumber: 66,
    symbol: "Dy",
    name: "Dysprosium",
    atomicMass: 162.5,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f¹⁰ 6s²",
    electronegativity: 1.22,
    oxidationStates: "+3",
    density: 8.55,
    meltingPoint: 1680,
    boilingPoint: 2840,
    yearDiscovered: 1886,
    discoverer: "Paul Émile Lecoq de Boisbaudran",
    description:
      "Dysprosium is a chemical element with symbol Dy and atomic number 66. It is a rare earth element with a metallic silver luster.",
  },
  {
    atomicNumber: 67,
    symbol: "Ho",
    name: "Holmium",
    atomicMass: 164.93,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f¹¹ 6s²",
    electronegativity: 1.23,
    oxidationStates: "+3",
    density: 8.8,
    meltingPoint: 1734,
    boilingPoint: 2993,
    yearDiscovered: 1878,
    discoverer: "Marc Delafontaine",
    description:
      "Holmium is a chemical element with symbol Ho and atomic number 67. Part of the lanthanide series, holmium is a rare-earth element.",
  },
  {
    atomicNumber: 68,
    symbol: "Er",
    name: "Erbium",
    atomicMass: 167.26,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f¹² 6s²",
    electronegativity: 1.24,
    oxidationStates: "+3",
    density: 9.07,
    meltingPoint: 1802,
    boilingPoint: 3141,
    yearDiscovered: 1843,
    discoverer: "Carl Gustaf Mosander",
    description:
      "Erbium is a chemical element with symbol Er and atomic number 68. A silvery-white solid metal when artificially isolated, natural erbium is always found in chemical combination with other elements.",
  },
  {
    atomicNumber: 69,
    symbol: "Tm",
    name: "Thulium",
    atomicMass: 168.93,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f¹³ 6s²",
    electronegativity: 1.25,
    oxidationStates: "+2, +3",
    density: 9.32,
    meltingPoint: 1818,
    boilingPoint: 2223,
    yearDiscovered: 1879,
    discoverer: "Per Teodor Cleve",
    description:
      "Thulium is a chemical element with symbol Tm and atomic number 69. It is the thirteenth and third-last element in the lanthanide series.",
  },
  {
    atomicNumber: 70,
    symbol: "Yb",
    name: "Ytterbium",
    atomicMass: 173.05,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f¹⁴ 6s²",
    electronegativity: 1.1,
    oxidationStates: "+2, +3",
    density: 6.9,
    meltingPoint: 1097,
    boilingPoint: 1469,
    yearDiscovered: 1878,
    discoverer: "Jean Charles Galissard de Marignac",
    description:
      "Ytterbium is a chemical element with symbol Yb and atomic number 70. It is the fourteenth and penultimate element in the lanthanide series.",
  },
  {
    atomicNumber: 71,
    symbol: "Lu",
    name: "Lutetium",
    atomicMass: 174.97,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "d",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹ 6s²",
    electronegativity: 1.27,
    oxidationStates: "+3",
    density: 9.84,
    meltingPoint: 1925,
    boilingPoint: 3675,
    yearDiscovered: 1907,
    discoverer: "Georges Urbain",
    description:
      "Lutetium is a chemical element with symbol Lu and atomic number 71. It is a silvery white metal, which resists corrosion in dry air, but not in moist air.",
  },
  {
    atomicNumber: 72,
    symbol: "Hf",
    name: "Hafnium",
    atomicMass: 178.49,
    category: "transition-metal",
    group: 4,
    period: 6,
    block: "d",
    electronConfiguration: "[Xe] 4f¹⁴ 5d² 6s²",
    electronegativity: 1.3,
    oxidationStates: "+4",
    density: 13.31,
    meltingPoint: 2506,
    boilingPoint: 4876,
    yearDiscovered: 1923,
    discoverer: "Dirk Coster",
    description:
      "Hafnium is a chemical element with symbol Hf and atomic number 72. A lustrous, silvery gray, tetravalent transition metal, hafnium chemically resembles zirconium and is found in many zirconium minerals.",
  },
  {
    atomicNumber: 73,
    symbol: "Ta",
    name: "Tantalum",
    atomicMass: 180.95,
    category: "transition-metal",
    group: 5,
    period: 6,
    block: "d",
    electronConfiguration: "[Xe] 4f¹⁴ 5d³ 6s²",
    electronegativity: 1.5,
    oxidationStates: "-1, +2, +3, +4, +5",
    density: 16.69,
    meltingPoint: 3290,
    boilingPoint: 5731,
    yearDiscovered: 1802,
    discoverer: "Anders Gustaf Ekeberg",
    description:
      "Tantalum is a chemical element with symbol Ta and atomic number 73. A rare, hard, blue-gray, lustrous transition metal, tantalum is highly corrosion-resistant.",
  },
  {
    atomicNumber: 74,
    symbol: "W",
    name: "Tungsten",
    atomicMass: 183.84,
    category: "transition-metal",
    group: 6,
    period: 6,
    block: "d",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁴ 6s²",
    electronegativity: 2.36,
    oxidationStates: "-2, -1, +1, +2, +3, +4, +5, +6",
    density: 19.25,
    meltingPoint: 3695,
    boilingPoint: 5828,
    yearDiscovered: 1783,
    discoverer: "Fausto Elhuyar",
    description:
      "Tungsten, or wolfram, is a chemical element with symbol W and atomic number 74. The name tungsten comes from the former Swedish name for the tungstate mineral scheelite, tungsten which means 'heavy stone'.",
  },
  {
    atomicNumber: 75,
    symbol: "Re",
    name: "Rhenium",
    atomicMass: 186.21,
    category: "transition-metal",
    group: 7,
    period: 6,
    block: "d",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁵ 6s²",
    electronegativity: 1.9,
    oxidationStates: "-3, -1, +1, +2, +3, +4, +5, +6, +7",
    density: 21.02,
    meltingPoint: 3459,
    boilingPoint: 5869,
    yearDiscovered: 1925,
    discoverer: "Masataka Ogawa",
    description:
      "Rhenium is a chemical element with symbol Re and atomic number 75. It is a silvery-white, heavy, third-row transition metal in group 7 of the periodic table.",
  },
  {
    atomicNumber: 76,
    symbol: "Os",
    name: "Osmium",
    atomicMass: 190.23,
    category: "transition-metal",
    group: 8,
    period: 6,
    block: "d",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁶ 6s²",
    electronegativity: 2.2,
    oxidationStates: "+2, +3, +4, +6, +8",
    density: 22.59,
    meltingPoint: 3306,
    boilingPoint: 5285,
    yearDiscovered: 1803,
    discoverer: "Smithson Tennant",
    description:
      "Osmium is a chemical element with symbol Os and atomic number 76. It is a hard, brittle, bluish-white transition metal in the platinum group that is found as a trace element in alloys, mostly in platinum ores.",
  },
  {
    atomicNumber: 77,
    symbol: "Ir",
    name: "Iridium",
    atomicMass: 192.22,
    category: "transition-metal",
    group: 9,
    period: 6,
    block: "d",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁷ 6s²",
    electronegativity: 2.2,
    oxidationStates: "-3, -1, +1, +2, +3, +4, +5, +6",
    density: 22.56,
    meltingPoint: 2719,
    boilingPoint: 4701,
    yearDiscovered: 1803,
    discoverer: "Smithson Tennant",
    description:
      "Iridium is a chemical element with symbol Ir and atomic number 77. A very hard, brittle, silvery-white transition metal of the platinum group, iridium is the second-densest element (after osmium).",
  },
  {
    atomicNumber: 78,
    symbol: "Pt",
    name: "Platinum",
    atomicMass: 195.08,
    category: "transition-metal",
    group: 10,
    period: 6,
    block: "d",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁹ 6s¹",
    electronegativity: 2.28,
    oxidationStates: "+2, +4, +6",
    density: 21.45,
    meltingPoint: 2041.4,
    boilingPoint: 4098,
    yearDiscovered: 1735,
    discoverer: "Antonio de Ulloa",
    description:
      "Platinum is a chemical element with symbol Pt and atomic number 78. It is a dense, malleable, ductile, highly unreactive, precious, silverish-white transition metal.",
  },
  {
    atomicNumber: 79,
    symbol: "Au",
    name: "Gold",
    atomicMass: 196.97,
    category: "transition-metal",
    group: 11,
    period: 6,
    block: "d",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
    electronegativity: 2.54,
    oxidationStates: "-1, +1, +3, +5",
    density: 19.3,
    meltingPoint: 1337.33,
    boilingPoint: 3243,
    yearDiscovered: null,
    discoverer: "Ancient",
    description:
      "Gold is a chemical element with symbol Au and atomic number 79. In its purest form, it is a bright, slightly reddish yellow, dense, soft, malleable, and ductile metal.",
  },
  {
    atomicNumber: 80,
    symbol: "Hg",
    name: "Mercury",
    atomicMass: 200.59,
    category: "transition-metal",
    group: 12,
    period: 6,
    block: "d",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
    electronegativity: 2.0,
    oxidationStates: "+1, +2",
    density: 13.534,
    meltingPoint: 234.32,
    boilingPoint: 629.88,
    yearDiscovered: null,
    discoverer: "Ancient",
    description:
      "Mercury is a chemical element with symbol Hg and atomic number 80. It is commonly known as quicksilver and was formerly named hydrargyrum.",
  },
  {
    atomicNumber: 81,
    symbol: "Tl",
    name: "Thallium",
    atomicMass: 204.38,
    category: "post-transition-metal",
    group: 13,
    period: 6,
    block: "p",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
    electronegativity: 1.62,
    oxidationStates: "+1, +3",
    density: 11.85,
    meltingPoint: 577,
    boilingPoint: 1746,
    yearDiscovered: 1861,
    discoverer: "William Crookes",
    description:
      "Thallium is a chemical element with symbol Tl and atomic number 81. This soft gray post-transition metal is not found free in nature.",
  },
  {
    atomicNumber: 82,
    symbol: "Pb",
    name: "Lead",
    atomicMass: 207.2,
    category: "post-transition-metal",
    group: 14,
    period: 6,
    block: "p",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
    electronegativity: 1.87,
    oxidationStates: "-4, +2, +4",
    density: 11.34,
    meltingPoint: 600.61,
    boilingPoint: 2022,
    yearDiscovered: null,
    discoverer: "Ancient",
    description:
      "Lead is a chemical element with symbol Pb and atomic number 82. It is a heavy metal that is denser than most common materials.",
  },
  {
    atomicNumber: 83,
    symbol: "Bi",
    name: "Bismuth",
    atomicMass: 208.98,
    category: "post-transition-metal",
    group: 15,
    period: 6,
    block: "p",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
    electronegativity: 2.02,
    oxidationStates: "-3, +3, +5",
    density: 9.78,
    meltingPoint: 544.7,
    boilingPoint: 1837,
    yearDiscovered: null,
    discoverer: "Ancient",
    description:
      "Bismuth is a chemical element with symbol Bi and atomic number 83. It is a pentavalent post-transition metal and one of the pnictogens with chemical properties resembling its lighter homologs arsenic and antimony.",
  },
  {
    atomicNumber: 84,
    symbol: "Po",
    name: "Polonium",
    atomicMass: 209,
    category: "post-transition-metal",
    group: 16,
    period: 6,
    block: "p",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
    electronegativity: 2.0,
    oxidationStates: "-2, +2, +4, +6",
    density: 9.32,
    meltingPoint: 527,
    boilingPoint: 1235,
    yearDiscovered: 1898,
    discoverer: "Marie Curie",
    description:
      "Polonium is a chemical element with symbol Po and atomic number 84. A rare and highly radioactive metal with no stable isotopes, polonium is chemically similar to selenium and tellurium.",
  },
  {
    atomicNumber: 85,
    symbol: "At",
    name: "Astatine",
    atomicMass: 210,
    category: "halogen",
    group: 17,
    period: 6,
    block: "p",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
    electronegativity: 2.2,
    oxidationStates: "-1, +1, +3, +5, +7",
    density: 7,
    meltingPoint: 575,
    boilingPoint: 610,
    yearDiscovered: 1940,
    discoverer: "Dale R. Corson",
    description:
      "Astatine is a chemical element with symbol At and atomic number 85. It is the rarest naturally occurring element in the Earth's crust, occurring only as the decay product of various heavier elements.",
  },
  {
    atomicNumber: 86,
    symbol: "Rn",
    name: "Radon",
    atomicMass: 222,
    category: "noble-gas",
    group: 18,
    period: 6,
    block: "p",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
    electronegativity: 2.2,
    oxidationStates: "+2",
    density: 0.00973,
    meltingPoint: 202,
    boilingPoint: 211.5,
    yearDiscovered: 1900,
    discoverer: "Friedrich Ernst Dorn",
    description:
      "Radon is a chemical element with symbol Rn and atomic number 86. It is a radioactive, colorless, odorless, tasteless noble gas.",
  },
  {
    atomicNumber: 87,
    symbol: "Fr",
    name: "Francium",
    atomicMass: 223,
    category: "alkali-metal",
    group: 1,
    period: 7,
    block: "s",
    electronConfiguration: "[Rn] 7s¹",
    electronegativity: 0.7,
    oxidationStates: "+1",
    density: 1.87,
    meltingPoint: 300,
    boilingPoint: 950,
    yearDiscovered: 1939,
    discoverer: "Marguerite Perey",
    description:
      "Francium is a chemical element with symbol Fr and atomic number 87. It was discovered by Marguerite Perey in France in 1939. It is the second-most electropositive element, behind only caesium, and is the second rarest naturally occurring element.",
  },
  {
    atomicNumber: 88,
    symbol: "Ra",
    name: "Radium",
    atomicMass: 226,
    category: "alkaline-earth-metal",
    group: 2,
    period: 7,
    block: "s",
    electronConfiguration: "[Rn] 7s²",
    electronegativity: 0.9,
    oxidationStates: "+2",
    density: 5.5,
    meltingPoint: 973,
    boilingPoint: 2010,
    yearDiscovered: 1898,
    discoverer: "Marie Curie",
    description:
      "Radium is a chemical element with symbol Ra and atomic number 88. It is the sixth element in group 2 of the periodic table, also known as the alkaline earth metals.",
  },
  {
    atomicNumber: 89,
    symbol: "Ac",
    name: "Actinium",
    atomicMass: 227,
    category: "actinide",
    group: 3,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 6d¹ 7s²",
    electronegativity: 1.1,
    oxidationStates: "+3",
    density: 10.07,
    meltingPoint: 1323,
    boilingPoint: 3471,
    yearDiscovered: 1899,
    discoverer: "André-Louis Debierne",
    description:
      "Actinium is a chemical element with symbol Ac and atomic number 89. It is a radioactive, silvery-white, metallic element.",
  },
  {
    atomicNumber: 90,
    symbol: "Th",
    name: "Thorium",
    atomicMass: 232.04,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 6d² 7s²",
    electronegativity: 1.3,
    oxidationStates: "+2, +3, +4",
    density: 11.7,
    meltingPoint: 2115,
    boilingPoint: 5061,
    yearDiscovered: 1829,
    discoverer: "Jöns Jakob Berzelius",
    description:
      "Thorium is a chemical element with symbol Th and atomic number 90. A radioactive actinide metal, thorium is one of only four radioactive elements that still occur naturally in large quantities as a primordial element.",
  },
  {
    atomicNumber: 91,
    symbol: "Pa",
    name: "Protactinium",
    atomicMass: 231.04,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f² 6d¹ 7s²",
    electronegativity: 1.5,
    oxidationStates: "+3, +4, +5",
    density: 15.37,
    meltingPoint: 1841,
    boilingPoint: 4300,
    yearDiscovered: 1913,
    discoverer: "Kasimir Fajans",
    description:
      "Protactinium is a chemical element with symbol Pa and atomic number 91. It is a dense, silvery-gray actinide metal which readily reacts with oxygen, water vapor and inorganic acids.",
  },
  {
    atomicNumber: 92,
    symbol: "U",
    name: "Uranium",
    atomicMass: 238.03,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f³ 6d¹ 7s²",
    electronegativity: 1.38,
    oxidationStates: "+3, +4, +5, +6",
    density: 19.1,
    meltingPoint: 1405.3,
    boilingPoint: 4404,
    yearDiscovered: 1789,
    discoverer: "Martin Heinrich Klaproth",
    description:
      "Uranium is a chemical element with symbol U and atomic number 92. It is a silvery-grey metal in the actinide series of the periodic table.",
  },
  {
    atomicNumber: 93,
    symbol: "Np",
    name: "Neptunium",
    atomicMass: 237,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f⁴ 6d¹ 7s²",
    electronegativity: 1.36,
    oxidationStates: "+3, +4, +5, +6, +7",
    density: 20.45,
    meltingPoint: 917,
    boilingPoint: 4273,
    yearDiscovered: 1940,
    discoverer: "Edwin McMillan",
    description:
      "Neptunium is a chemical element with symbol Np and atomic number 93. A radioactive actinide metal, neptunium is the first transuranic element.",
  },
  {
    atomicNumber: 94,
    symbol: "Pu",
    name: "Plutonium",
    atomicMass: 244,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f⁶ 7s²",
    electronegativity: 1.28,
    oxidationStates: "+3, +4, +5, +6, +7",
    density: 19.85,
    meltingPoint: 912.5,
    boilingPoint: 3505,
    yearDiscovered: 1940,
    discoverer: "Glenn T. Seaborg",
    description:
      "Plutonium is a radioactive chemical element with symbol Pu and atomic number 94. It is an actinide metal of silvery-gray appearance that tarnishes when exposed to air.",
  },
  {
    atomicNumber: 95,
    symbol: "Am",
    name: "Americium",
    atomicMass: 243,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f⁷ 7s²",
    electronegativity: 1.3,
    oxidationStates: "+2, +3, +4, +5, +6",
    density: 13.69,
    meltingPoint: 1449,
    boilingPoint: 2880,
    yearDiscovered: 1944,
    discoverer: "Glenn T. Seaborg",
    description:
      "Americium is a radioactive chemical element with symbol Am and atomic number 95. It is a transuranic member of the actinide series, in the periodic table located under the lanthanide element europium.",
  },
  {
    atomicNumber: 96,
    symbol: "Cm",
    name: "Curium",
    atomicMass: 247,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f⁷ 6d¹ 7s²",
    electronegativity: 1.3,
    oxidationStates: "+3, +4",
    density: 13.51,
    meltingPoint: 1613,
    boilingPoint: 3383,
    yearDiscovered: 1944,
    discoverer: "Glenn T. Seaborg",
    description:
      "Curium is a radioactive chemical element with symbol Cm and atomic number 96. It is a hard, dense, silvery metal with a relatively high melting point and boiling point for an actinide.",
  },
  {
    atomicNumber: 97,
    symbol: "Bk",
    name: "Berkelium",
    atomicMass: 247,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f⁹ 7s²",
    electronegativity: 1.3,
    oxidationStates: "+3, +4",
    density: 14.79,
    meltingPoint: 1259,
    boilingPoint: 2900,
    yearDiscovered: 1949,
    discoverer: "Glenn T. Seaborg",
    description:
      "Berkelium is a transuranic radioactive chemical element with symbol Bk and atomic number 97. It is a member of the actinide and transuranium element series.",
  },
  {
    atomicNumber: 98,
    symbol: "Cf",
    name: "Californium",
    atomicMass: 251,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f¹⁰ 7s²",
    electronegativity: 1.3,
    oxidationStates: "+2, +3, +4",
    density: 15.1,
    meltingPoint: 1173,
    boilingPoint: 1743,
    yearDiscovered: 1950,
    discoverer: "Glenn T. Seaborg",
    description:
      "Californium is a radioactive chemical element with symbol Cf and atomic number 98. The element was first synthesized in 1950 at the Lawrence Berkeley National Laboratory.",
  },
  {
    atomicNumber: 99,
    symbol: "Es",
    name: "Einsteinium",
    atomicMass: 252,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f¹¹ 7s²",
    electronegativity: 1.3,
    oxidationStates: "+2, +3",
    density: 8.84,
    meltingPoint: 1133,
    boilingPoint: 1269,
    yearDiscovered: 1952,
    discoverer: "Albert Ghiorso",
    description:
      "Einsteinium is a synthetic element with symbol Es and atomic number 99. It is the seventh transuranic element, and an actinide.",
  },
  {
    atomicNumber: 100,
    symbol: "Fm",
    name: "Fermium",
    atomicMass: 257,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f¹² 7s²",
    electronegativity: 1.3,
    oxidationStates: "+2, +3",
    density: null,
    meltingPoint: 1800,
    boilingPoint: null,
    yearDiscovered: 1952,
    discoverer: "Albert Ghiorso",
    description:
      "Fermium is a synthetic element with symbol Fm and atomic number 100. It is an actinide and the heaviest element that can be formed by neutron bombardment of lighter elements.",
  },
  {
    atomicNumber: 101,
    symbol: "Md",
    name: "Mendelevium",
    atomicMass: 258,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f¹³ 7s²",
    electronegativity: 1.3,
    oxidationStates: "+2, +3",
    density: null,
    meltingPoint: 1100,
    boilingPoint: null,
    yearDiscovered: 1955,
    discoverer: "Albert Ghiorso",
    description:
      "Mendelevium is a synthetic element with symbol Md and atomic number 101. A metallic radioactive transuranic element in the actinide series, it is the first element that currently cannot be produced in macroscopic quantities.",
  },
  {
    atomicNumber: 102,
    symbol: "No",
    name: "Nobelium",
    atomicMass: 259,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f¹⁴ 7s²",
    electronegativity: 1.3,
    oxidationStates: "+2, +3",
    density: null,
    meltingPoint: 1100,
    boilingPoint: null,
    yearDiscovered: 1958,
    discoverer: "Albert Ghiorso",
    description:
      "Nobelium is a synthetic chemical element with symbol No and atomic number 102. It is named in honor of Alfred Nobel, the inventor of dynamite and benefactor of science.",
  },
  {
    atomicNumber: 103,
    symbol: "Lr",
    name: "Lawrencium",
    atomicMass: 262,
    category: "actinide",
    group: null,
    period: 7,
    block: "d",
    electronConfiguration: "[Rn] 5f¹⁴ 7s² 7p¹",
    electronegativity: 1.3,
    oxidationStates: "+3",
    density: null,
    meltingPoint: 1900,
    boilingPoint: null,
    yearDiscovered: 1961,
    discoverer: "Albert Ghiorso",
    description:
      "Lawrencium is a synthetic chemical element with symbol Lr and atomic number 103. It is named in honor of Ernest Lawrence, inventor of the cyclotron, a device that was used to discover many artificial radioactive elements.",
  },
  {
    atomicNumber: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    atomicMass: 267,
    category: "transition-metal",
    group: 4,
    period: 7,
    block: "d",
    electronConfiguration: "[Rn] 5f¹⁴ 6d² 7s²",
    electronegativity: null,
    oxidationStates: "+4",
    density: 23.2,
    meltingPoint: 2400,
    boilingPoint: 5800,
    yearDiscovered: 1964,
    discoverer: "Joint Institute for Nuclear Research",
    description:
      "Rutherfordium is a chemical element with symbol Rf and atomic number 104, named in honor of physicist Ernest Rutherford. It is a synthetic element and radioactive.",
  },
  {
    atomicNumber: 105,
    symbol: "Db",
    name: "Dubnium",
    atomicMass: 270,
    category: "transition-metal",
    group: 5,
    period: 7,
    block: "d",
    electronConfiguration: "[Rn] 5f¹⁴ 6d³ 7s²",
    electronegativity: null,
    oxidationStates: "+5",
    density: 29.3,
    meltingPoint: null,
    boilingPoint: null,
    yearDiscovered: 1967,
    discoverer: "Joint Institute for Nuclear Research",
    description:
      "Dubnium is a chemical element with symbol Db and atomic number 105. It is a synthetic element and radioactive.",
  },
  {
    atomicNumber: 106,
    symbol: "Sg",
    name: "Seaborgium",
    atomicMass: 271,
    category: "transition-metal",
    group: 6,
    period: 7,
    block: "d",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁴ 7s²",
    electronegativity: null,
    oxidationStates: "+6",
    density: 35.0,
    meltingPoint: null,
    boilingPoint: null,
    yearDiscovered: 1974,
    discoverer: "Lawrence Berkeley Laboratory",
    description:
      "Seaborgium is a synthetic chemical element with symbol Sg and atomic number 106. It is named after the American nuclear chemist Glenn T. Seaborg.",
  },
  {
    atomicNumber: 107,
    symbol: "Bh",
    name: "Bohrium",
    atomicMass: 270,
    category: "transition-metal",
    group: 7,
    period: 7,
    block: "d",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁵ 7s²",
    electronegativity: null,
    oxidationStates: "+7",
    density: 37.1,
    meltingPoint: null,
    boilingPoint: null,
    yearDiscovered: 1981,
    discoverer: "Gesellschaft für Schwerionenforschung",
    description:
      "Bohrium is a chemical element with symbol Bh and atomic number 107. It is a synthetic element that is not found in nature.",
  },
  {
    atomicNumber: 108,
    symbol: "Hs",
    name: "Hassium",
    atomicMass: 269,
    category: "transition-metal",
    group: 8,
    period: 7,
    block: "d",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁶ 7s²",
    electronegativity: null,
    oxidationStates: "+8",
    density: 41.0,
    meltingPoint: null,
    boilingPoint: null,
    yearDiscovered: 1984,
    discoverer: "Gesellschaft für Schwerionenforschung",
    description:
      "Hassium is a synthetic chemical element with symbol Hs and atomic number 108. It is named after the German state of Hesse where it was discovered.",
  },
  {
    atomicNumber: 109,
    symbol: "Mt",
    name: "Meitnerium",
    atomicMass: 278,
    category: "transition-metal",
    group: 9,
    period: 7,
    block: "d",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁷ 7s²",
    electronegativity: null,
    oxidationStates: "+3, +6",
    density: 37.4,
    meltingPoint: null,
    boilingPoint: null,
    yearDiscovered: 1982,
    discoverer: "Gesellschaft für Schwerionenforschung",
    description:
      "Meitnerium is a synthetic chemical element with symbol Mt and atomic number 109. It is named after Lise Meitner, an Austrian-Swedish physicist and mathematician.",
  },
  {
    atomicNumber: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    atomicMass: 281,
    category: "transition-metal",
    group: 10,
    period: 7,
    block: "d",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁸ 7s²",
    electronegativity: null,
    oxidationStates: "+6",
    density: 34.8,
    meltingPoint: null,
    boilingPoint: null,
    yearDiscovered: 1994,
    discoverer: "Gesellschaft für Schwerionenforschung",
    description:
      "Darmstadtium is a synthetic chemical element with symbol Ds and atomic number 110. It is named after Darmstadt, Germany, where it was discovered.",
  },
  {
    atomicNumber: 111,
    symbol: "Rg",
    name: "Roentgenium",
    atomicMass: 282,
    category: "transition-metal",
    group: 11,
    period: 7,
    block: "d",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁹ 7s²",
    electronegativity: null,
    oxidationStates: "+3",
    density: 28.7,
    meltingPoint: null,
    boilingPoint: null,
    yearDiscovered: 1994,
    discoverer: "Gesellschaft für Schwerionenforschung",
    description:
      "Roentgenium is a synthetic chemical element with symbol Rg and atomic number 111. It is named after Wilhelm Conrad Röntgen, who discovered X-rays.",
  },
  {
    atomicNumber: 112,
    symbol: "Cn",
    name: "Copernicium",
    atomicMass: 285,
    category: "transition-metal",
    group: 12,
    period: 7,
    block: "d",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
    electronegativity: null,
    oxidationStates: "+2, +4",
    density: 23.7,
    meltingPoint: null,
    boilingPoint: null,
    yearDiscovered: 1996,
    discoverer: "Gesellschaft für Schwerionenforschung",
    description:
      "Copernicium is a synthetic chemical element with symbol Cn and atomic number 112. It is named after astronomer Nicolaus Copernicus.",
  },
  {
    atomicNumber: 113,
    symbol: "Nh",
    name: "Nihonium",
    atomicMass: 286,
    category: "post-transition-metal",
    group: 13,
    period: 7,
    block: "p",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
    electronegativity: null,
    oxidationStates: "+1, +3, +5",
    density: 16,
    meltingPoint: 700,
    boilingPoint: 1400,
    yearDiscovered: 2004,
    discoverer: "RIKEN",
    description:
      "Nihonium is a synthetic chemical element with symbol Nh and atomic number 113. It was discovered by Japanese scientists, and its name comes from Nihon, the Japanese word for Japan.",
  },
  {
    atomicNumber: 114,
    symbol: "Fl",
    name: "Flerovium",
    atomicMass: 289,
    category: "post-transition-metal",
    group: 14,
    period: 7,
    block: "p",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
    electronegativity: null,
    oxidationStates: "+2, +4",
    density: 14,
    meltingPoint: 340,
    boilingPoint: 420,
    yearDiscovered: 1999,
    discoverer: "Joint Institute for Nuclear Research",
    description:
      "Flerovium is a synthetic chemical element with symbol Fl and atomic number 114. It is named after the Flerov Laboratory of Nuclear Reactions where it was discovered.",
  },
  {
    atomicNumber: 115,
    symbol: "Mc",
    name: "Moscovium",
    atomicMass: 290,
    category: "post-transition-metal",
    group: 15,
    period: 7,
    block: "p",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
    electronegativity: null,
    oxidationStates: "+1, +3",
    density: 13.5,
    meltingPoint: 670,
    boilingPoint: 1400,
    yearDiscovered: 2004,
    discoverer: "Joint Institute for Nuclear Research",
    description:
      "Moscovium is a synthetic chemical element with symbol Mc and atomic number 115. It is named after the Moscow Oblast, where the Joint Institute for Nuclear Research is located.",
  },
  {
    atomicNumber: 116,
    symbol: "Lv",
    name: "Livermorium",
    atomicMass: 293,
    category: "post-transition-metal",
    group: 16,
    period: 7,
    block: "p",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
    electronegativity: null,
    oxidationStates: "+2, +4",
    density: 12.9,
    meltingPoint: 709,
    boilingPoint: 1085,
    yearDiscovered: 2000,
    discoverer: "Joint Institute for Nuclear Research",
    description:
      "Livermorium is a synthetic chemical element with symbol Lv and atomic number 116. It is named after the Lawrence Livermore National Laboratory in the United States.",
  },
  {
    atomicNumber: 117,
    symbol: "Ts",
    name: "Tennessine",
    atomicMass: 294,
    category: "halogen",
    group: 17,
    period: 7,
    block: "p",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
    electronegativity: null,
    oxidationStates: "-1, +1, +3, +5",
    density: 7.2,
    meltingPoint: 723,
    boilingPoint: 883,
    yearDiscovered: 2010,
    discoverer: "Joint Institute for Nuclear Research",
    description:
      "Tennessine is a synthetic chemical element with symbol Ts and atomic number 117. It is named after the state of Tennessee in the United States.",
  },
  {
    atomicNumber: 118,
    symbol: "Og",
    name: "Oganesson",
    atomicMass: 294,
    category: "noble-gas",
    group: 18,
    period: 7,
    block: "p",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
    electronegativity: null,
    oxidationStates: "+2, +4, +6",
    density: 5,
    meltingPoint: 325,
    boilingPoint: 450,
    yearDiscovered: 2006,
    discoverer: "Joint Institute for Nuclear Research",
    description:
      "Oganesson is a synthetic chemical element with symbol Og and atomic number 118. It is named after Yuri Oganessian, a Russian nuclear physicist.",
  },
]

